//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4241
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_w {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class arch_config : global::System.Configuration.ApplicationSettingsBase {
        
        private static arch_config defaultInstance = ((arch_config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new arch_config())));
        
        public static arch_config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user id=gd;password=gd2013;server=.\\SQLSERVER2008;Trusted_Connection=yes;database" +
            "=GD2C2013;")]
        public string strConn {
            get {
                return ((string)(this["strConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-01-01 11:00:00.000")]
        public string fecha {
            get {
                return ((string)(this["fecha"]));
            }
        }
    }
}
